### ISSUE TITLE
Clash with PIR usermod

### ISSUE THREAD

**Issue by smcgann99** [sgupta999/wled-alexa-relay-usermod#2]
Hi,

Sorry to bother you again, I compiled with PIR usermod, but this doesn't seem to work at all, even if your mod is unticked.

Is it likely that you mod breaks this ?

**Comment by sgupta999** [comment]
nope i have the PIR mode running on my own system - the only file i have changed alexa.cpp has nothing to do with PIR mod. make sure you follow the instruction for that it is complex. Make sure it is not inactive in the info gui - there are three setting within that mod that could make it inactive

**Comment by smcgann99** [comment]
Fair enough, I can get it to switch on once after a reboot (but never turns off again) After manually switching off, pir will not turn it on again.
What device are you running on - I have an esp32 dev build.

**Comment by sgupta999** [comment]
same thing - are you using a logic level shifter to up the voltage? I am assuming you have tried to run the PIR and confirm its working outside the WLED setup. Also assuming you have common ground for wleed, psu, relay and PIR - just listing all the issues I had to work through. I have sound reactive mic too  - so had to run both 3.3 and 5v lines with common ground from the board

**Comment by smcgann99** [comment]
I'm just testing on breadboard, the pir gpio is just shorted to ground to simulate pir. On first trigger switches on PIR mod. Then no Off or retrigger works ???

**Comment by smcgann99** [comment]
perhaps you could share your bin file if it all works for you ?

**Comment by sgupta999** [comment]
my bin file has ssid/passwd hardcoded - plus its been a couple of months I dont  even remember. What PIR are u using? check the jumper settings on that or likely PIR is busted

**Comment by smcgann99** [comment]
If pir works for you with your mod I'm not sure why it doesn't for me, never mind, I'll just use built in button option.

Would be nice if you could get your mod included into official build, as extra Alexa relays could be hand for many people.

**Comment by sgupta999** [comment]
if its not working for you standalone with the breadboard the PIR could have a hardware issue - it could be busted. if you have another one handy try that.

**Comment by smcgann99** [comment]
I'm not even using a pir just a jumper wire so its not a hardware issue.

What version of firmware did you build yours with, I might try that, as it seems a bit unstable, very long loading times on web gui

**Comment by sgupta999** [comment]
not sure what you mean by just using a jumper wire - anywhere attached is the binary i am using
[soundReactive_WLED_0.13.3_ESP32.zip](https://github.com/sgupta999/wled-alexa-relay-usermod/files/12101044/soundReactive_WLED_0.13.3_ESP32.zip)
